version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - test
    environment:
      - RAILS_ENV=development
    volumes:
      - ./bin:/app/bin
      - ./app:/app/app
      - ./db:/app/db
      - ./config:/app/config
      - ./public:/app/public
  solr:
    image: solr
    ports:
      - "8983:8983"
    networks:
      - test
    volumes:
      - ./data:/var/solr
volumes:
  data:
networks:
  test:
    driver: bridge
